
on: push
name: Deploy Koro-Filipino Wordpress
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: dmitstudent.ca
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol:ftps
          server-dir: /public_html/devsite/



 
     
